### ISSUE TITLE
Fix Sound looping

### ISSUE THREAD

**Issue by playduck** [StereoBeast/Project0815#1]
**Issue**
Sound does not loop correctly when using the following snippet:
```java
Sound s = new Sound("path/to/some/soundfile.wav");
s.play(-1, 1);
```
The sound is supposed to start over immediately after stopping. What is happening however is that there is a slight delay before the sound restarts. While this issue isn't particularly important for music. It is, however, absolutely _gemebraking_ when trying to use short, looping samples in regards to engine sounds.

**Steps to reproduce**

- add the aforementioned code snippet to the constructor of some class like _Game_ or _Car_.
- replace the sample path to an actual sound file (i recommend a concise file intended for looping)
- (optional) comment out other possibly distracting sound, e.g. music

**Comment by StereoBeast** [comment]
Use stereobeast.Methods.playSound(String path, int Count, double volume, int ID) instead.
This only works for .wav Files but the looping should be better!

**Comment by StereoBeast** [comment]
Use this instead:
`stereobeast.Methods.playSound(String path, int times, double volume, int ID);`

This only works for wav files but the looping should be better.
